"""Step 2: run the layered assessment.

Input:
    benchmark/benchmark_metadata.csv generated by 01_prepare_benchmark.py.
    The deterministic task definitions are rebuilt from pyassess_core.py to
    keep tests and AST rules available during evaluation.

Outputs:
    results/submission_level_results.csv
    results/baseline_results.csv
    results/holdout_evaluation.csv
    results/layer_contribution.csv
    results/hidden_test_gain_by_label.csv
    results/ast_contribution_by_category.csv
"""

from pathlib import Path

import pandas as pd

from pyassess_core import (
    BENCHMARK,
    RESULTS,
    acceptable_diagnosis,
    build_records,
    build_tasks,
    evaluate_record,
    metrics_for,
)


def require_benchmark() -> None:
    metadata = BENCHMARK / "benchmark_metadata.csv"
    if not metadata.exists():
        raise FileNotFoundError(
            "benchmark/benchmark_metadata.csv was not found. Run 01_prepare_benchmark.py first."
        )


def main() -> None:
    require_benchmark()
    records = build_records(build_tasks())

    eval_rows = []
    for record in records:
        result = evaluate_record(record)
        row = {k: v for k, v in record.items() if k not in ["code", "visible", "hidden", "forbidden_names"]}
        row.update(result)
        row["diagnostic_aligned"] = acceptable_diagnosis(row["primary_label"], row["observed_diagnosis"])
        eval_rows.append(row)

    df = pd.DataFrame(eval_rows)
    df.to_csv(RESULTS / "submission_level_results.csv", index=False)

    methods = [
        ("visible_only", "accepted_visible_only"),
        ("visible_plus_hidden", "accepted_visible_hidden"),
        ("visible_hidden_ast_full", "accepted_full"),
    ]
    baseline_rows = []
    splits = [
        ("all", df),
        ("development", df[df["split"] == "development"]),
        ("holdout", df[df["split"] == "holdout"]),
    ]
    for split_name, split_df in splits:
        for method_name, column in methods:
            metrics = metrics_for(split_df, column)
            metrics.update({"split": split_name, "method": method_name})
            baseline_rows.append(metrics)
    pd.DataFrame(baseline_rows).to_csv(RESULTS / "baseline_results.csv", index=False)
    pd.DataFrame([r for r in baseline_rows if r["split"] in ["development", "holdout"]]).to_csv(
        RESULTS / "holdout_evaluation.csv", index=False
    )

    incorrect = df[~df["ground_truth_accept"]]
    visible_false_accept = int(incorrect["accepted_visible_only"].sum())
    hidden_false_accept = int(incorrect["accepted_visible_hidden"].sum())
    full_false_accept = int(incorrect["accepted_full"].sum())
    layer_rows = [
        {"layer": "visible tests", "new_rejections": int((~incorrect["accepted_visible_only"]).sum()), "remaining_false_accept": visible_false_accept},
        {"layer": "hidden tests", "new_rejections": visible_false_accept - hidden_false_accept, "remaining_false_accept": hidden_false_accept},
        {"layer": "AST constraints", "new_rejections": hidden_false_accept - full_false_accept, "remaining_false_accept": full_false_accept},
    ]
    pd.DataFrame(layer_rows).to_csv(RESULTS / "layer_contribution.csv", index=False)

    hidden_rows = []
    for label, group in incorrect.groupby("primary_label"):
        visible_accept = int(group["accepted_visible_only"].sum())
        hidden_reject = int(((group["accepted_visible_only"] == True) & (group["accepted_visible_hidden"] == False)).sum())
        hidden_rows.append({
            "primary_label": label,
            "incorrect_submissions": len(group),
            "visible_false_accepts": visible_accept,
            "hidden_rejections_among_visible_false_accepts": hidden_reject,
            "hidden_test_gain": hidden_reject / visible_accept if visible_accept else 0.0,
        })
    pd.DataFrame(hidden_rows).to_csv(RESULTS / "hidden_test_gain_by_label.csv", index=False)

    ast_rows = []
    ast_mask = (incorrect["accepted_visible_hidden"] == True) & (incorrect["accepted_full"] == False)
    for category, group in incorrect.groupby("category"):
        ast_caught = int((ast_mask.loc[group.index]).sum())
        ast_rows.append({
            "category": category,
            "incorrect_submissions": len(group),
            "ast_caught": ast_caught,
            "ast_contribution_rate": ast_caught / len(group) if len(group) else 0.0,
        })
    pd.DataFrame(ast_rows).to_csv(RESULTS / "ast_contribution_by_category.csv", index=False)

    print("Step 2 completed: layered assessment results generated.")
    print(f"Submission-level results: {RESULTS / 'submission_level_results.csv'}")


if __name__ == "__main__":
    main()
