"""Step 3: analyze diagnostic alignment and representative cases.

Input:
    results/submission_level_results.csv generated by 02_run_assessment.py.

Outputs:
    results/diagnostic_cross_table_long.csv
    results/diagnostic_alignment_by_label.csv
    results/diagnostic_alignment.csv
    results/case_studies.csv
"""

import pandas as pd

from pyassess_core import RESULTS


def require_submission_results() -> None:
    path = RESULTS / "submission_level_results.csv"
    if not path.exists():
        raise FileNotFoundError(
            "results/submission_level_results.csv was not found. Run 02_run_assessment.py first."
        )


def main() -> None:
    require_submission_results()
    df = pd.read_csv(RESULTS / "submission_level_results.csv")

    diagnostic_cross = df.groupby(["primary_label", "observed_diagnosis"]).size().reset_index(name="count")
    diagnostic_cross.to_csv(RESULTS / "diagnostic_cross_table_long.csv", index=False)

    alignment_rows = []
    for label, group in df.groupby("primary_label"):
        alignment_rows.append({
            "primary_label": label,
            "n": len(group),
            "aligned": int(group["diagnostic_aligned"].sum()),
            "alignment_rate": float(group["diagnostic_aligned"].mean()),
            "observed_diagnoses": "; ".join(f"{k}:{v}" for k, v in group["observed_diagnosis"].value_counts().items()),
        })
    pd.DataFrame(alignment_rows).to_csv(RESULTS / "diagnostic_alignment_by_label.csv", index=False)
    pd.DataFrame([{
        "overall_n": len(df),
        "aligned": int(df["diagnostic_aligned"].sum()),
        "diagnostic_alignment_rate": float(df["diagnostic_aligned"].mean()),
        "diagnostic_completeness_rate": float((df["observed_diagnosis"].astype(str).str.len() > 0).mean()),
    }]).to_csv(RESULTS / "diagnostic_alignment.csv", index=False)

    selected = [
        ("visible_overfit", "A submission hard-codes or memorizes public examples and returns an arbitrary fallback for unseen inputs."),
        ("boundary_error", "A submission is correct for ordinary inputs but fails a boundary input such as zero, empty sequence, or one-element list."),
        ("constraint_violation", "A submission produces correct outputs but violates the intended structural requirement by using a prohibited shortcut."),
        ("nontermination", "A submission contains a deterministic nontermination pattern that must be handled by pre-checks or timeout mechanisms."),
    ]
    case_rows = []
    for variant, explanation in selected:
        sample = df[df["variant"] == variant].iloc[0]
        case_rows.append({
            "case_type": variant,
            "task_id": sample["task_id"],
            "task_title": sample["task_title"],
            "category": sample["category"],
            "baseline_visible_only": "accepted" if sample["accepted_visible_only"] else "rejected",
            "visible_hidden": "accepted" if sample["accepted_visible_hidden"] else "rejected",
            "full_framework": "accepted" if sample["accepted_full"] else "rejected",
            "observed_diagnosis": sample["observed_diagnosis"],
            "interpretation": explanation,
        })
    pd.DataFrame(case_rows).to_csv(RESULTS / "case_studies.csv", index=False)

    print("Step 3 completed: diagnostic analysis generated.")
    print(f"Diagnostic alignment: {RESULTS / 'diagnostic_alignment.csv'}")


if __name__ == "__main__":
    main()
