"""Step 4: run runtime, timeout, and environment checks.

Input:
    benchmark/benchmark_metadata.csv generated by 01_prepare_benchmark.py.
    The deterministic task definitions are rebuilt from pyassess_core.py for
    internal scalability checks.

Outputs:
    results/internal_scalability.csv
    results/subprocess_timeout_demo.csv
    results/parallel_throughput.csv
    results/execution_mode_interpretation.csv
    results/manuscript_environment_windows.csv
    results/run_summary.csv
"""

import platform
import sys
import time

import pandas as pd

from pyassess_core import (
    BENCHMARK,
    RESULTS,
    build_records,
    build_tasks,
    execution_mode_rows,
    internal_scalability,
    manuscript_environment_row,
    parallel_throughput,
    run_subprocess_timeout_demo,
)


def require_benchmark() -> None:
    metadata = BENCHMARK / "benchmark_metadata.csv"
    if not metadata.exists():
        raise FileNotFoundError(
            "benchmark/benchmark_metadata.csv was not found. Run 01_prepare_benchmark.py first."
        )


def main() -> None:
    require_benchmark()
    start = time.perf_counter()
    records = build_records(build_tasks())

    internal_scalability(records)
    run_subprocess_timeout_demo()
    parallel_throughput(records)

    pd.DataFrame(execution_mode_rows()).to_csv(RESULTS / "execution_mode_interpretation.csv", index=False)
    pd.DataFrame([manuscript_environment_row()]).to_csv(RESULTS / "manuscript_environment_windows.csv", index=False)

    elapsed = time.perf_counter() - start
    pd.DataFrame([{
        "step": "04_runtime_checks.py",
        "elapsed_seconds_observed": elapsed,
        "python_runtime_observed": sys.version.split()[0],
        "platform_observed": platform.platform(),
        "note": "Manuscript environment is recorded in manuscript_environment_windows.csv based on the confirmed Windows CPU-only machine."
    }]).to_csv(RESULTS / "run_summary.csv", index=False)

    print("Step 4 completed: runtime and protocol outputs generated.")
    print(f"Runtime summary: {RESULTS / 'run_summary.csv'}")


if __name__ == "__main__":
    main()
